[git]
  tag_sort = "semver"    # sort tags by SemVer

[parser]
  merges = "exclude"     # ignore merge commits
  tag_match = "^v?\\d+\\.\\d+\\.\\d+"

[output]
  file = ""              # leave empty to emit to stdout
  format = "markdown"    # ensure valid GitHub-flavored Markdown

[group."ğŸš€ Features"]
  commit = "feat"

[group."ğŸ› Bug Fixes"]
  commit = "fix"

[group."ğŸ“ Documentation"]
  commit = "docs"

[group."âš™ï¸ Maintenance"]
  commit = "chore"

[release]
  include = ["body"]     # include commit bodies